- name: Play 1 - Python Install library
  hosts: docker-master
  become: yes
  tasks:
    - name: Install Python 3.6
      yum:
        name: python36
        state: present
      tags: python-install

    - name: alternatives
      alternatives:
        name: python
        link: /usr/bin/python3.6
        path: /usr/bin/python3
      tags: python-alternatives

- name: Play 2 - Python library install and copying of War file
  hosts: docker-master
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install boto3 and botocore with pip3 module
      pip:
        name:
          - boto
          - boto3
          - botocore
        executable: pip3.6
      tags: boto-lib-install

    - name: copy the war file
      aws_s3:
        bucket: lwplabs-artifacts-webapp
        object: LoginRegisterApp.war
        dest: /tmp/{{ job_name }}
        mode: get
      tags: copy-war
